services:
  postgres:
    image: postgres:16-alpine
    container_name: besewu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: besewu
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: besewu
    ports:
      - "5434:5432"
    volumes:
      - besewu-pg-data:/var/lib/postgresql/data

volumes:
  besewu-pg-data:
